# --- POST MENU ITEMS ---

[[main]]
name = "Posts"
pageRef = "posts"
weight = 100

# --- END POST MENU ---



# --- GUIDELINES MENU ---

[[main]]
name = "Template Guidelines"
pageRef = "guidelines"
weight = 200

[[main]]
name = "Architecture overview"
parent = "Guidelines"
pageRef = "guidelines/architecture-overview"
weight = 201

[[main]]
name = "Backend API setup"
parent = "Guidelines"
pageRef = "guidelines/backend-api-setup"
weight = 202

[[main]]
name = "Blowfish Theme Guide"
parent = "Guidelines"
pageRef = "guidelines/blowfish-theme-guide"
weight = 203

[[main]]
name = "Environment Configuration"
parent = "Guidelines"
pageRef = "guidelines/environment-configuration"
weight = 204

[[main]]
name = "Environment Quick Reference"
parent = "Guidelines"
pageRef = "guidelines/environment-quick-reference"
weight = 205

[[main]]
name = "Environment Variables"
parent = "Guidelines"
pageRef = "guidelines/environment-varaibles"
weight = 206

[[main]]
name = "ESLint & Prettier Guide"
parent = "Guidelines"
pageRef = "guidelines/eslint-prettier-guide"
weight = 207

[[main]]
name = "Fast Build Guide"
parent = "Guidelines"
pageRef = "guidelines/fast-build-guide"
weight = 208

[[main]]
name = "HTMX Bundled vs CDN"
parent = "Guidelines"
pageRef = "guidelines/htmx-bundled-vs-cdn"
weight = 209

[[main]]
name = "HTMX Quick Reference"
parent = "Guidelines"
pageRef = "guidelines/htmx-quick-reference"
weight = 210

[[main]]
name = "HTMX Web Components Architecture"
parent = "Guidelines"
pageRef = "guidelines/htmx-web-components-architecture"
weight = 211

[[main]]
name = "Quick Start New Tools"
parent = "Guidelines"
pageRef = "guidelines/quick-start-new-tools"
weight = 212

[[main]]
name = "Recommended Tools"
parent = "Guidelines"
pageRef = "guidelines/recommended-tools"
weight = 213

[[main]]
name = "SCSS Best Practices"
parent = "Guidelines"
pageRef = "guidelines/scss-best-practices"
weight = 214

[[main]]
name = "State Management Implementation"
parent = "Guidelines"
pageRef = "guidelines/state-management-implementation"
weight = 215

[[main]]
name = "State Management Guide"
parent = "Guidelines"
pageRef = "guidelines/state-management-guide"
weight = 216

# --- END GUIDELINES MENU ---



# --- PROJECTS MENU ITEMS ---

[[main]]
name = "Projects"
pageRef = "projects"
weight = 20

[[main]]
name = "An interesting topic"
parent = "Posts"
pageRef = "posts/interesting-topic"
weight = 21

[[main]]
name = "An interesting topic 2"
parent = "Posts"
pageRef = "posts/interesting-topic"
weight = 22

# --- END PROJECTS MENU ---



# --- ABOUT MENU ITEMS ---

[[main]]
name = "About"
pageRef = "about"
weight = 30

# --- END ABOUT MENU ---



# --- END OTHER MENU ITEMS ---



# --- SUBNAVIGATION EXAMPLE ---

[[subnavigation]]
name = "Sub ordrered menu item"
pageRef = "posts/welcome"

[[footer]]
none = "none"
